Models/ViewModel/PCCViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ControlHrsConsultoria.Models.ViewModel
{
    public class PCCViewModel
    {
        public int idDetalle { get; set; }
        [StringLength(100)]
        [Display(Name = "Descripción")]
        public string descripcion { get; set; }
        [Display(Name = "Fecha de Inicio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<DateTime> fechaInicio { get; set; }
        [Display(Name = "Fecha de Finalización")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<DateTime> fechaFinal { get; set; }
        [Required]
        [Range(0, 999.99)]
        [Display(Name = "Cantidad de Horas")]
        public Nullable<decimal> cantidadHrs { get; set; }
    }
}

Controllers/PCCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControlHrsConsultoria.Models;
using ControlHrsConsultoria.Models.ViewModel;

namespace ControlHrsConsultoria.Controllers
{
    public class PCCController : Controller
    {
        // GET: Consultor
        public ActionResult Index()
        {
            List<ListPCCViewModel> lst;
            using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
            {
                lst = (from d in db.Proyecto_Consultor_Cliente
                       select new ListPCCViewModel
                       {
                           idDetalle = d.idDetalle,
                           idProyecto = (int)d.idProyecto,
                           idConsultor = (int)d.idConsultor,
                           idPerfil = (int)d.idPerfil,
                           idCliente = (int)d.idCliente,
                           montoPrecio = d.montoPrecio,
                           costo = d.costo,
                           descripcion = d.descripcion,
                           fechaInicio = d.fechaInicio,
                           fechaFinal = d.fechaFinal,
                           cantidadHrs = d.cantidadHrs
                       }).ToList();
            }
            return View(lst);
        }
        public ActionResult Editar(int id)
        {
            PCCViewModel model = new PCCViewModel();
            using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
            {
                var oTabla = db.Proyecto_Consultor_Cliente.Find(id);
                model.descripcion = oTabla.descripcion;
                model.fechaInicio = oTabla.fechaInicio;
                model.fechaFinal = oTabla.fechaFinal;
                model.cantidadHrs = oTabla.cantidadHrs;
                model.idDetalle = oTabla.idDetalle;
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Editar(PCCViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    decimal horas;
                    using (ControlHrsConsultoriaEntities db = new ControlHrsConsultoriaEntities())
                    {
                        var oTabla = db.Proyecto_Consultor_Cliente.Find(model.idDetalle);
                        horas = (decimal)oTabla.cantidadHrs + (decimal)model.cantidadHrs;
                        oTabla.idDetalle = oTabla.idDetalle;
                        oTabla.idProyecto = oTabla.idProyecto;
                        oTabla.idConsultor = oTabla.idConsultor;
                        oTabla.idPerfil = oTabla.idPerfil;
                        oTabla.montoPrecio = oTabla.montoPrecio;
                        oTabla.costo = oTabla.costo;
                        oTabla.descripcion = model.descripcion;
                        oTabla.fechaInicio = model.fechaInicio;
                        oTabla.fechaFinal = model.fechaFinal;
                        oTabla.cantidadHrs = horas;
                        oTabla.idCliente = oTabla.idCliente;

                        db.Entry(oTabla).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/PCC/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Inner exception: {0}", ex.InnerException);
                throw new Exception(ex.Message);
            }
        }
    }
}

Views/PCC/Editar.cshtml
@model ControlHrsConsultoria.Models.ViewModel.PCCViewModel
@{
    ViewBag.Title = "Editar";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "PCC", FormMethod.Post))
{

    <div class="row">
        <div class="col-md-12">
            @Html.HiddenFor(d => d.idDetalle)

            <div class="form-group">
                @Html.LabelFor(d => d.descripcion)
                @Html.TextBoxFor(d => d.descripcion, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.descripcion, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.fechaInicio)
                @Html.EditorFor(d => d.fechaInicio, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.fechaInicio, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.fechaFinal)
                @Html.EditorFor(d => d.fechaFinal, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.fechaFinal, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(d => d.cantidadHrs)
                @Html.TextBoxFor(d => d.cantidadHrs, "", new { @type = "number", @step = "any", @class = "form-control" })
                @Html.ValidationMessageFor(d => d.cantidadHrs, null, new { @class = "text-danger" })
            </div>

            <div class="row" />
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
                <a href="~/PCC/" class="btn btn-danger">Cancelar</a>
            </div>
        </div>
    </div>

}

Views/PCC/Index.cshtml
@model List<ControlHrsConsultoria.Models.ViewModel.ListPCCViewModel>
@{
    ViewBag.Title = "Proyectos asignados";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#Detalle</th>
                <th>#Proyecto</th>
                <th>#Consultor</th>
                <th>#Perfil</th>
                <th>#Cliente</th>
                <th>Monto Precio</th>
                <th>Costo</th>
                <th>Descripción</th>
                <th class="cntr">Fecha de Inicio</th>
                <th class="cntr">Fecha Final</th>
                <th>Cantidad de Horas</th>
                <th>Accion</th>
            </tr>
            @foreach(var oElemento in Model)
            {
                <tr>
                    <td class="cntr">@oElemento.idDetalle</td>
                    <td class="cntr">@oElemento.idProyecto</td>
                    <td class="cntr">@oElemento.idConsultor</td>
                    <td class="cntr">@oElemento.idPerfil</td>
                    <td class="cntr">@oElemento.idCliente</td>
                    <td class="cntr">@oElemento.montoPrecio</td>
                    <td class="cntr">@oElemento.costo</td>
                    <td>@oElemento.descripcion</td>
                    <td class="cntr">@oElemento.fechaInicio</td>
                    <td class="cntr">@oElemento.fechaFinal</td>
                    <td class="cntr">@oElemento.cantidadHrs</td>
                    <td><a class="btn btn-default" href="~/PCC/Editar/@oElemento.idDetalle">Editar</a></td>
                </tr>
            }
        </table>
    </div>
</div>

<style>
    .cntr {
        text-align: center;
    }
</style>